import { createElement, checkbox } from '../ui/element.js';
import { REPORT_FILENAME_STEM } from '../brand.js';
import { captureDisclosureState, restoreDisclosureState } from '../view-state.js';
import { createSequentialQueue } from './queue.js';
import { BatchWorkerClient } from './client.js';
import { SEMANTIC_MODELS,getSemanticModel } from '../engine/models.js';
const el=(tag,text='',cls='')=>createElement(tag,cls,text);
const button=(label,fn,id)=>{const b=el('button',label,'secondary');b.type='button';if(id)b.id=id;b.onclick=fn;return b;};
const download=(value,name)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
export class BatchView {
  constructor({onOpen=()=>{},onOwnership=()=>{},onState=()=>{},onClear=()=>{}}={}) {
    this.onOpen=onOpen;this.onOwnership=onOwnership;this.onState=onState;this.onClear=onClear;this.files=new Map();this.generation=0;this.client=new BatchWorkerClient();this.settings={useAI:false,modelId:'minilm',checks:['title','subject','keywords']};this.root=el('section','','batch-panel');this.header=el('div');this.list=el('div','','batch-items');this.status=el('p');this.status.setAttribute('role','status');this.controls=el('div','','flow-actions');this.setup=el('div','','batch-setup');this.root.append(this.header,this.setup,this.status,this.controls,this.list);
    this.hiddenEvents=0;document.addEventListener('visibilitychange',()=>{if(document.hidden&&this.busy)this.hiddenEvents++;});this.createQueue();this.render();
  }
  createQueue(){const generation=++this.generation;this.queue=createSequentialQueue({analyze:(...args)=>this.client.analyze(...args),screen:(...args)=>this.client.screen(...args),hash:(...args)=>this.client.hash(...args),dispose:()=>this.client.dispose(),getConditions:()=>({visibility:document.visibilityState,hiddenEvents:this.hiddenEvents}),onEvent:e=>{if(generation!==this.generation)return;if(e.type==='item-removed')this.files.delete(e.id);if(e.type==='destroyed')this.files.clear();this.render();this.onState(e.state);if(e.type==='queue-started')this.message('Queue started. PDFs are checked one at a time.');else if(e.type==='queue-idle')this.message('Queue finished its available work. Inspect outcomes or add more PDFs.');else if(e.type==='queue-paused')this.message(e.state.modelFailure?'Queue paused: choose how to recover optional AI.':e.state.budget.pendingSerializedBytes?'Queue paused: choose which details to retain.':'Queue paused. Completed outcomes are retained; continue when ready.');else if(e.type==='pause-requested')this.message('Pause requested. The current PDF will finish first.');if(['queue-idle','queue-paused'].includes(e.type))this.client.dispose();}});}
  get busy(){return this.queue.snapshot().running;}
  get state(){return this.queue.snapshot();}
  async releaseIdleWorkers(){if(!this.busy)await this.client.dispose();}
  act(fn){try{const result=fn();result?.catch(e=>this.message(e.message));}catch(e){this.message(e.message);}}
  message(text){this.status.textContent=text;}
  add(files){try{const input=Array.from(files);const ids=this.queue.enqueue(input);ids.forEach((id,i)=>this.files.set(id,input[i]));this.render();this.message(`${ids.length} PDF${ids.length===1?'':'s'} added. Nothing starts until you choose Start queue.`);}catch(e){this.message(e.message);}}
  async clear(){++this.generation;this.queue.stopAll();await this.queue.destroy();this.files.clear();this.consentValue=false;this.onClear();this.createQueue();this.render();this.message('Queue cleared. Source handles and retained details released; no data was saved.');}
  async start(){const s=this.state;if(s.configuration){this.onOwnership();return this.act(()=>this.queue.resume());}if(this.settings.useAI&&!this.consent?.checked){this.message('Authorize the displayed optional downloads, or leave AI screening off.');this.consent?.focus();return;}this.onOwnership();this.act(()=>this.queue.start(structuredClone(this.settings)));}
  open(id){const report=this.queue.getReport(id) || this.queue.getPendingReport?.(id),file=this.files.get(id);if(!report || !file){this.message('Detailed report was released or is awaiting a budget decision; compact summary remains available.');return;}this.onOpen(report,file,id);}
  render(){
    const disclosures=captureDisclosureState(this.root);const active=document.activeElement,focus=this.root.contains(active)?active.id:null,s=this.state;const justStarted=Boolean(s.configuration)&&!this.hadConfiguration;this.hadConfiguration=Boolean(s.configuration);const configurationOpen=justStarted?false:this.root.querySelector('#batch-configuration')?.open,admissionOpen=justStarted?false:this.root.querySelector('#batch-admission')?.open;this.header.replaceChildren();this.setup.replaceChildren();this.controls.replaceChildren();this.list.replaceChildren();if(s.configuration)this.root.append(this.setup);else this.root.insertBefore(this.setup,this.status);
    const drop=el('div','','batch-drop');const label=el('label','Choose PDFs or drop several here');label.htmlFor='batch-files';const picker=el('input');picker.id='batch-files';picker.type='file';picker.multiple=true;picker.accept='application/pdf,.pdf';picker.onchange=()=>{this.add(picker.files);picker.value='';};drop.append(label,picker,el('p','Up to 20 files · 300 MB total · 50 MB each · engine limit 200 pages per file','model-note'));drop.ondragover=e=>{e.preventDefault();};drop.ondrop=e=>{e.preventDefault();e.stopPropagation();this.add(e.dataTransfer.files);};const counts=Object.fromEntries(['completed','failed','canceled','skipped','queued'].map(status=>[status,s.items.filter(i=>i.status===status).length]));const finished=counts.completed+counts.failed+counts.canceled+counts.skipped;const overview=el('section','','batch-overview');overview.setAttribute('aria-label','Queue progress');overview.append(el('h3',`${finished} of ${s.items.length} PDFs finished`),el('p',`${counts.completed} complete · ${counts.failed} incomplete/failed · ${counts.canceled} canceled · ${counts.skipped} skipped · ${counts.queued} waiting${s.activeId?' · 1 current':''}`));if(s.items.length){const overall=el('progress');overall.max=s.items.length;overall.value=finished;overall.setAttribute('aria-label','Finished PDFs');overview.append(overall);}overview.append(el('p',s.running?(s.paused?'Pausing after the current PDF.':'Processing the current PDF; files run sequentially.'):s.modelFailure?'Paused for a model-initialization decision.':s.budget.pendingSerializedBytes?'Paused for a report-retention decision.':!s.configuration?'Ready to start; nothing has run.':s.paused?'Queue paused. Continue when ready.':'Queue idle.'));this.header.append(overview);const admission=el('details','','batch-admission');admission.id='batch-admission';admission.open=admissionOpen ?? !s.configuration;admission.append(el('summary',s.items.length?'Add PDFs to this queue':'Choose PDFs'),drop);admission.firstChild.id='batch-admission-toggle';this.setup.append(admission,el('p','Foreground session only. Closing or reloading loses this queue. Background tabs or sleep can delay processing; no background-completion guarantee.','model-note'));
    const settings=el('fieldset','','batch-settings');settings.disabled=Boolean(s.configuration);settings.append(el('legend','Queue settings (frozen when started)'));
    const use=el('label');const ai=el('input');ai.type='checkbox';checkbox(ai);ai.id='batch-use-ai';ai.checked=this.settings.useAI;ai.onchange=()=>{this.settings.useAI=ai.checked;this.render();};use.append(ai,document.createTextNode(' Optional local AI screening'));settings.append(use);
    const select=el('select');select.id='batch-model';select.setAttribute('aria-label','Batch screening model');for(const m of SEMANTIC_MODELS){const o=el('option',`${m.label} · ${m.language}`);o.value=m.key;select.append(o);}select.value=this.settings.modelId;select.disabled=!this.settings.useAI;select.onchange=()=>{this.settings.modelId=select.value;this.consentValue=false;this.render();};settings.append(select);
    const model=getSemanticModel(this.settings.modelId);settings.append(el('p',`${model.label}: ${(model.graphBytes/1e6).toFixed(2)} MB model + ${(model.tokenizerBytes/1e6).toFixed(2)} MB tokenizer; runtime approximately26.86 MB uncompressed, separate. ${model.tradeoff}`.replace('approximately26','approximately 26'),'model-note'),el('p','Each PDF’s declared language controls model eligibility. Missing or unsupported language stays uncertain; no model is silently substituted. Relatedness is advisory and thresholds are provisional. PDF text stays on this device; assets download from external hosts.','model-note'));
    const checks=el('div','','screening-checks');for(const [key,text] of [['title','Title'],['subject','Subject'],['keywords','Each keyword'],['sections','Bounded tagged sections']]){const row=el('label'),input=el('input');input.type='checkbox';checkbox(input);input.id=`batch-check-${key}`;input.checked=this.settings.checks.includes(key);input.disabled=!this.settings.useAI;input.onchange=()=>{this.settings.checks=input.checked?[...this.settings.checks,key]:this.settings.checks.filter(k=>k!==key);};row.append(input,document.createTextNode(text));checks.append(row);}settings.append(checks);
    const consentRow=el('label');this.consent=el('input');this.consent.type='checkbox';checkbox(this.consent);this.consent.id='batch-consent';this.consent.checked=Boolean(this.consentValue);this.consent.onchange=()=>this.consentValue=this.consent.checked;consentRow.append(this.consent,document.createTextNode(' I authorize the displayed optional model/tokenizer downloads for this queue.'));if(this.settings.useAI)settings.append(consentRow);const configuration=el('details','','batch-configuration');configuration.id='batch-configuration';configuration.open=configurationOpen ?? false;configuration.append(el('summary',s.configuration?'Run settings and download receipt':'Optional AI settings · traditional checks run by default'),settings);configuration.firstChild.id='batch-configuration-toggle';this.setup.append(configuration);
    if(s.configuration)this.setup.append(el('p',`This run: ${s.configuration.useAI?getSemanticModel(s.configuration.modelId).label:'Traditional checks only'}${s.configuration.useAI?` · ${(s.configuration.checks || []).join(', ')}`:''}`,'frozen-settings'));
    const pending=s.items.filter(i=>i.status==='queued');const start=button(s.configuration?'Continue queue':'Start queue',()=>{if(this.settings.useAI&&!this.settings.checks.length&&!s.configuration){this.message('Select at least one AI check or turn AI off.');return;}this.start();},'batch-start');start.disabled=s.running||!pending.length||Boolean(s.modelFailure)||s.budget.pendingSerializedBytes>0;
    const pause=button('Pause after current PDF',()=>this.queue.pause(),'batch-pause');pause.disabled=!s.running||s.paused;
    const cancel=button('Cancel current PDF',()=>this.queue.cancelActive(),'batch-cancel');cancel.disabled=!s.activeId;
    const stop=button('Stop all',()=>{this.queue.stopAll();this.client.dispose();},'batch-stop');stop.disabled=!s.running;
    const clear=button('Clear queue and release data',()=>this.clear(),'batch-clear');const summary=button('Download compact batch JSON',()=>download(this.state,`${REPORT_FILENAME_STEM}-batch-summary.json`),'batch-summary');summary.disabled=!s.items.length;
    start.classList.add('primary-action');start.hidden=Boolean(s.configuration)&&!pending.length;pause.hidden=!s.running;cancel.hidden=!s.activeId;stop.hidden=!s.running;clear.classList.add('batch-secondary-action');this.controls.append(start,pause,cancel,stop,summary,clear);
    const resources=el('details','','batch-resources');resources.append(el('summary','Report retention and resource limits'),el('p',`Retained detailed reports: ${(s.budget.estimatedSerializedBytes/1e6).toFixed(2)} / ${(s.budget.limit/1e6).toFixed(2)} MB serialized estimate. This excludes source handles, pending spill, runtime/model heaps, and parsed-page memory; it is not RAM measurement.`,'model-note'));resources.dataset.disclosureKey='batch-resources';resources.firstChild.id='batch-resources-toggle';configuration.append(resources);
    if(s.modelFailure){const panel=el('section','','batch-decision');panel.append(el('h3','Optional model initialization failed'),el('p',s.modelFailure.message),button('Retry model initialization',()=>{this.onOwnership();this.act(()=>this.queue.resolveModelFailure({action:'retry'}));},'batch-retry-model'),button('Continue remaining PDFs without AI',()=>{this.onOwnership();this.act(()=>this.queue.resolveModelFailure({action:'structural-only'}));},'batch-structural-only'));this.header.append(panel);}
    if(s.budget.pendingSerializedBytes){const panel=el('section','','batch-decision');panel.append(el('h3','Choose what to retain before continuing'),el('p',`One completed pending report requires ${(s.budget.pendingSerializedBytes/1e6).toFixed(2)} MB beyond the retained serialized budget. Scheduling is paused; no report was silently discarded.`),button('Download compact summary first',()=>download(this.state,`${REPORT_FILENAME_STEM}-batch-before-release.json`),'batch-pressure-summary'),button('Keep pending detail after releasing selected old reports',()=>{if(!this.queue.retainPending())this.message('Not enough serialized budget. Export and explicitly release old details, or retain this item as summary only.');},'batch-retain-pending'),button('Discard pending detail; keep its summary',()=>this.queue.summarizePending({consent:true}),'batch-summary-only'));this.header.append(panel);}
    for(const item of s.items){const card=el('article','','batch-item');card.dataset.queueId=item.id;card.append(el('h3',item.name),el('p',`${item.status==='completed'?'Complete':item.status==='failed'?'Incomplete / failed':item.status} · ${(item.bytes/1e6).toFixed(2)} MB`,'batch-status'));const technical=el('details','','batch-file-details');technical.dataset.disclosureKey=`batch-technical-${item.id}`;technical.append(el('summary','File identity, timing and compact outcomes'),el('p',`${item.id} · ${item.phase}`));if(item.sourceHash)technical.append(el('p',`SHA-256 ${item.sourceHash}`,'batch-hash'));
      if(item.progress && item.id===s.activeId){const p=item.progress;card.append(el('p',p.message || p.phase || p.stage || 'Processing'));if(p.total>0 && Number.isFinite(p.completed)){const meter=el('progress');meter.max=p.total;meter.value=p.completed;meter.setAttribute('aria-label',`${item.name} progress`);card.append(meter,el('p',`${p.completed} / ${p.total} ${p.unit || 'units'}`,'model-note'));}else {const meter=el('progress');meter.removeAttribute('value');meter.setAttribute('aria-label',`${item.name} preparing`);card.append(meter);}}
      if(item.timing?.finishedAt)technical.append(el('p',`Observed elapsed: ${Math.round(item.timing.elapsedMs || 0)} ms. Includes scheduling/visibility effects; not an ETA or speed guarantee.`,'model-note'));
      if(item.error)card.append(el('p',item.error,'error-message'));
      if(item.summary){card.append(el('p',item.summary.analysisComplete===true?`Text profile ${item.summary.profile}: ${item.summary.accepted?'Yes':'No'} · ${item.summary.pages ?? 'unknown'} pages.`:'Analysis incomplete: compliance was not established. The retained report explains the failed or unassessed required checks.'));const c=item.summary.findingCounts || {};card.append(el('p',`${c['required-defect'] || 0} required defects · ${c['required-indeterminate'] || 0} required checks needing review · ${c['advisory-concern'] || 0} advisory concerns · ${c.uncertain || 0} uncertain · ${c.unassessed || 0} unassessed`));for(const [field,value] of Object.entries(item.summary.advisories || {})){if(value)technical.append(el('p',`${field}: ${value.status}`,'model-note'));}if(item.summary.semantic?.error)card.append(el('p',`Optional AI did not complete: ${item.summary.semantic.error}`,'error-message')); const details=el('details');details.dataset.disclosureKey=`batch-compact-${item.id}`;details.append(el('summary','Compact retained outcomes'));details.firstChild.id=`batch-compact-toggle-${item.id}`;const pre=el('pre',JSON.stringify(item.summary,null,2));details.append(pre);technical.append(details);}
      const actions=el('div','','flow-actions');const management=el('details','','batch-file-management');management.dataset.disclosureKey=`batch-management-${item.id}`;management.append(el('summary','Retry, release or remove this PDF'));const maintenance=el('div','','flow-actions');management.append(maintenance);if(item.status==='awaiting-budget')actions.append(button('Inspect/export pending detail (temporary copy)',()=>this.open(item.id),`batch-open-${item.id}`),el('p','Opening makes one extra temporary report copy outside the serialized budget. Export it before discarding details.','model-note'));if(item.detailRetained){const open=button('Review findings',()=>this.open(item.id),`batch-open-${item.id}`);open.classList.add('primary-action');actions.append(open);maintenance.append(button('Release detail; keep compact summary',()=>this.queue.releaseDetails([item.id],{consent:true}),`batch-release-${item.id}`));}else if(item.summary)actions.append(el('p',item.status==='awaiting-budget'?'Detail awaits your budget choice.':'Only compact summary retained; detailed review/images are unavailable.','model-note'));
      if(item.id!==s.modelFailure?.id && ['failed','canceled','skipped','completed'].includes(item.status))maintenance.append(button('Retry PDF',()=>this.act(()=>this.queue.retry(item.id)),`batch-retry-${item.id}`));
      if(item.status==='queued'){const index=pending.findIndex(i=>i.id===item.id);for(const [label,delta] of [['Move earlier',-1],['Move later',1]]){const b=button(label,()=>{const ids=pending.map(i=>i.id);[ids[index],ids[index+delta]]=[ids[index+delta],ids[index]];this.act(()=>this.queue.reorder(ids));},`batch-move-${item.id}-${delta}`);b.disabled=index+delta<0||index+delta>=pending.length;actions.append(b);}actions.append(button('Skip PDF',()=>this.queue.skip(item.id),`batch-skip-${item.id}`));}
      if(item.id!==s.activeId&&item.id!==s.modelFailure?.id&&item.status!=='awaiting-budget')maintenance.append(button('Remove PDF',()=>this.act(()=>this.queue.remove(item.id)),`batch-remove-${item.id}`));technical.firstChild.id=`batch-technical-toggle-${item.id}`;management.firstChild.id=`batch-management-toggle-${item.id}`;card.append(actions,technical);if(maintenance.childElementCount)card.append(management);this.list.append(card);
    }
    restoreDisclosureState(this.root,disclosures);if(focus)document.getElementById(focus)?.focus({preventScroll:true});
  }
}
