const spec={label:'Adobe PDF properties guide',url:'https://helpx.adobe.com/acrobat/desktop/edit-documents/edit-pdf-properties/pdf-properties.html'};
const tags={label:'Acrobat content and tags guide',url:'https://helpx.adobe.com/acrobat/using/editing-document-structure-content-tags.html'};
export const HELP_TOPICS={
  attachments:{title:'Embedded and associated files',text:['Embedded files are separate payloads inside a PDF. Associated File declarations can link a file to the document or a particular object; references may also point to files that are not embedded.','Filename, media type, description and relationship are declarations. This inventory does not open, extract, decompress, analyse, certify, or establish the safety of attached contents. Describe how each file should be used; a description alone does not prove usable machine instructions.'],references:[{label:'PDF Association: files inside PDF',url:'https://pdfa.org/files-inside-pdf/'},{label:'Associated Files application note (PDF)',url:'https://pdfa.org/wp-content/uploads/2018/10/PDF20_AN002-AF.pdf'}]},
  info:{title:'Info metadata',text:['The PDF document-information dictionary stores basic fields such as Title, Author, Subject, and Keywords. It is separate from XMP metadata.','These are declared values, not proof of what the publication contains. They may be absent or out of date; missing Info fields do not by themselves make a PDF invalid.'],references:[spec]},
  xmp:{title:'XMP metadata',text:['XMP is embedded extensible metadata, serialized as XML/RDF. It can include titles in different languages and an ordered list of creators.','Info and XMP can disagree. Compare both with the publication and correct the source export rather than treating either declaration as ground truth.'],references:[{label:'Adobe XMP overview',url:'https://developer.adobe.com/xmp/docs/'},{label:'XMP specifications',url:'https://developer.adobe.com/xmp/docs/xmp-specifications/'}]},
  tags:{title:'Tagged PDF content',text:['Tags assign logical roles and connect them to page content. P means paragraph; H1–H6 are heading levels; Lbl is a list label. These roles are assigned by the producing tool, not proof that the text has the right meaning or is an authenticated byline.','Tags can be missing, incomplete, or wrong even when the visual page looks correct.'],references:[tags]},
  taggedOrder:{title:'Tagged reading order',text:['This sequence follows the recovered logical tag tree. It can differ from the order in which page drawing and text instructions occur.','A connected tag tree does not prove that its reading order is intended or correct. Compare dependent steps with the visual page and authoring source.'],references:[tags,{label:'Acrobat reading-order guide',url:'https://helpx.adobe.com/acrobat/using/touch-reading-order-tool-pdfs.html'}]},
  contentStream:{title:'Content-stream extraction',text:['A PDF content stream contains drawing and text instructions. This tool recovers text in their encountered sequence. Parser decoding, grouping, and recovery mean this is not byte-for-byte raw stream data.','That sequence is reproducible extraction evidence, not proof of intended reading order, visibility, identity, or factual correctness.'],references:[tags,{label:'PDF basics cheat sheet (PDF)',url:'https://pdfa.org/download-area/cheat-sheets/Basics.pdf'}]},
  profile:{title:'Text actionability profile',text:['Yes means every required rule passed for this tool’s supported text profile. No can mean a detected required defect or a condition whose compliance was not established.','This is not PDF/UA certification or an overall AI-readiness verdict. Publication identity, intended reading order, and downstream AI accuracy remain separate.'],references:[]},
  rules:{title:'Extracted evidence and traditional rules',text:['Parsing and string or structural comparisons run without a language model. This makes the execution traceable; it does not establish semantic truth.','Recovered publication candidates and normalization policies can miss or flag legitimate content. Inspect the compared values and source page.'],references:[spec]},
  heuristic:{title:'Rule-based heuristic',text:['A heuristic applies bounded clues to recovered PDF evidence. Author checks identify explicit first-page byline candidates; order checks look for limited numbered or spatial anomalies.','A candidate byline is not authenticated authorship. An order clue is not a complete reading-order audit. These findings require inspection, even though no AI model produced them.'],references:[tags]},
  ai:{title:'Optional local AI relatedness',text:['The browser model creates text embeddings and compares bounded excerpts. It estimates topical relatedness, not authorship, identity, factual truth, or the probability that a finding is correct.','Only a recorded inference marks a check as AI-assisted. Choosing a model, using a rules fast path, or skipping an unsupported check does not mean that model ran. Opening this help downloads no model.'],references:[{label:'Transformers.js documentation',url:'https://huggingface.co/docs/transformers.js/index'}]},
  bounded:{title:'Unassessed or bounded scope',text:['This check may be unrequested, unsupported for the declared language, outside a selected bound, or unavailable after an error. A selected model is configuration, not evidence that inference ran.','Unassessed is not a pass or an AI judgment. Use the full receipt to distinguish actual completed checks from selection preferences and skipped work.'],references:[{label:'Transformers.js documentation',url:'https://huggingface.co/docs/transformers.js/index'}]},
};
