// Real engine output for the story page, taken from the shipped samples. Run: node scripts/snapshot-story.js
// test/story-snapshot.test.js rebuilds this in memory and fails if the engine or samples drift from it.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import * as pdfjs from 'pdfjs-dist/legacy/build/pdf.mjs';
import { PDFDocument, PDFName, PDFDict, PDFArray, decodePDFRawStream } from 'pdf-lib';
import { analyzePdf } from '../src/engine/analyze.js';
import { normalizeFindings } from '../src/review/findings.js';
import { findingGroups, groupFigureFindings, groupHeadingFindings, reviewSummary, fixCard } from '../src/review/workspace.js';

const samples = new URL('../public/samples/', import.meta.url);
const bytes = async name => new Uint8Array(await readFile(new URL(`${name}.pdf`, samples)));
const clean = text => String(text || '').replace(/\s+/g, ' ').trim();

async function review(name) {
  const report = await analyzePdf(await bytes(name), { fileName: `${name}.pdf` });
  const groups = groupFigureFindings(groupHeadingFindings(findingGroups(normalizeFindings(report).findings)));
  const summary = reviewSummary(report, groups);
  const pins = [...summary.buckets.fix, ...summary.buckets.check].map((item, index) => {
    const card = fixCard(item, report);
    return { number: index + 1, bucket: index < summary.buckets.fix.length ? 'fix' : 'check', title: card.title, where: card.where };
  });
  return { report, headline: summary.headline, pins };
}
const tagSteps = (report, page) => (report.pages.find(item => item.number === page)?.logicalBlocks || [])
  .map(block => clean(block.text)).filter(text => /^\d[.)]\s/.test(text));
const drawnLines = (report, page) => (report.pages.find(item => item.number === page)?.blocks || [])
  .map(block => clean(block.text)).filter(Boolean);

export async function buildStorySnapshot() {
  const well = await review('well-prepared');
  const partly = await review('partly-prepared');
  const scrambled = await review('image-chart-scrambled-text');
  const travel = await review('built-to-travel');
  const fonts = fileURLToPath(new URL('../node_modules/pdfjs-dist/standard_fonts/', import.meta.url));
  const task = pdfjs.getDocument({ data: await bytes('built-to-travel'), isEvalSupported: false, standardFontDataUrl: fonts });
  const document = await task.promise;
  const outline = await document.getOutline();
  await task.destroy();
  // Read the attached CSV with pdf-lib (the same parser the engine's attachment inventory uses).
  const lib = await PDFDocument.load(await bytes('built-to-travel'), { updateMetadata: false });
  const names = lib.catalog.lookup(PDFName.of('Names'), PDFDict)?.lookup(PDFName.of('EmbeddedFiles'), PDFDict)?.lookup(PDFName.of('Names'), PDFArray);
  let csvText = '';
  for (let i = 0; names && i < names.size(); i += 2) {
    const spec = names.lookup(i + 1, PDFDict);
    if (!/\.csv$/.test(spec.lookup(PDFName.of('UF'))?.decodeText?.() || '')) continue;
    csvText = new TextDecoder().decode(decodePDFRawStream(spec.lookup(PDFName.of('EF'), PDFDict).lookup(PDFName.of('F'))).decode());
  }
  const figureAlt = report => report.figureAlternatives?.items?.find(item => item.tagged)?.alt || null;
  return {
    source: 'Generated by scripts/snapshot-story.js from public/samples; synthetic example data.',
    well: { headline: well.headline, figureAlt: figureAlt(well.report), chartLabels: drawnLines(well.report, 1).filter(text => /^(\d\.\d m|North|Central|South)$/.test(text)) },
    partly: { headline: partly.headline, figureAlt: figureAlt(partly.report), tagSteps: tagSteps(partly.report, 2), pins: partly.pins, savedTitle: partly.report.metadata.infoTitle },
    scrambled: {
      headline: scrambled.headline, figureAlt: figureAlt(scrambled.report), tagSteps: tagSteps(scrambled.report, 2),
      drawnLines: drawnLines(scrambled.report, 2).filter(text => !/^(SYNTHETIC|Original fictional|\d \/ \d)/.test(text)),
      pins: scrambled.pins,
    },
    travel: {
      headline: travel.headline,
      title: travel.report.metadata.infoTitle, authors: travel.report.metadata.author, language: travel.report.metadata.language,
      attachments: (travel.report.attachments?.files || []).map(file => ({ name: file.unicodeFilename || file.filename, description: file.description })),
      csvRows: csvText.trim().split('\n').filter(Boolean).map(row => row.split(',')),
      bookmarks: (outline || []).map(item => item.title),
    },
  };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const snapshot = await buildStorySnapshot();
  await writeFile(new URL('../src/story/snapshot.json', import.meta.url), `${JSON.stringify(snapshot, null, 2)}\n`);
  console.log('Wrote src/story/snapshot.json');
}
